version: "3.8"

services:
  mongo:
    image: mongo:7
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  # backend:
  #   build: ./backend
  #   container_name: spring_app
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/mydb
  #   depends_on:
  #     - mongo

volumes:
  mongo_data:
